---
- name: copy daemon install package
  copy: src=daemon_0.6.4-1_amd64.deb dest=/tmp/daemon_0.6.4-1_amd64.deb owner=root group=root mode=0644

- name: install daemon
  command: /usr/bin/dpkg -i /tmp/daemon_0.6.4-1_amd64.deb

- name: copy jenkins install package
  copy: src=jenkins_1.577_all.deb dest=/tmp/jenkins_1.577_all.deb owner=root group=root mode=0644

- name: copy jenkins cli
  copy: src=jenkins-cli.jar dest=/tmp/jenkins-cli.jar owner=root group=root mode=0644

- name: install jenkins
  command: /usr/bin/dpkg -i /tmp/jenkins_1.577_all.deb

- file: path={{ jenkins.updates }} state=directory owner=jenkins group=jenkins mode=0755

- name: update jenkins update center
  get_url:  url=http://updates.jenkins-ci.org/update-center.json force=yes dest={{ jenkins.updates }} owner=jenkins group=jenkins mode=0644

- name: config jenkins update center
  shell: /bin/grep connectionCheckUrl {{ jenkins.updates }}/update-center.json > {{ jenkins.updates}}/default.json

- file: path={{ jenkins.updates }}/default.json state=file owner=jenkins group=jenkins mode=0644

- template: src=jenkins-config.xml dest={{ jenkins.home }}/config.xml owner=jenkins group=jenkins mode=0644
  notify:
    - 'Restart Jenkins'

- wait_for: port=49187 delay=5

- name: Install plugins
  sudo: yes
  shell: java -jar {{ jenkins.cli_dest }} -s http://localhost:8080 install-plugin {{item}}
  with_items: 
     - git

- template: src=job-config.xml dest=/tmp/job-config.xml 

- name: Install job 
  shell: java -jar {{ jenkins.cli_dest }} -s http://localhost:8080 create-job cinnamon < /tmp/job-config.xml 
